### ISSUE TITLE
rename from Flight to Flights  (SQLServer Deployment is using dbo.Flights)

### ISSUE THREAD

**Issue by Jalalhejazi** [MicrosoftLearning/20487D-Developing-Microsoft-Azure-and-Web-Services#135]
CREATE TABLE [dbo].[Flights] 
-> maps to 
Flights in public DbSet<Flight> Flights { get; set; }

https://github.com/MicrosoftLearning/20487D-Developing-Microsoft-Azure-and-Web-Services/blob/d420c0a58a43d34aefd9d048499fd0f3696982ce/AllFiles/Mod01/Labfiles/Exercise1/Solution/BlueYonder.Flights/Models/FlightsContext.cs#L13

**Comment by slavBarkal** [comment]
fixed
