### ISSUE TITLE
Module 4 Lab function GetAvaliabileByDate only returns rooms that have at least one reservation

### ISSUE THREAD

**Issue by Ceribia** [MicrosoftLearning/20487D-Developing-Microsoft-Azure-and-Web-Services#137]
If \AllFiles\Mod04\LabFiles\Lab1\Starter\BlueYonder.Hotels\BlueYonder.Hotels.DAL\Repository\HotelBookingRepository.cs there is a function GetAvaliabileByDate that is supposed to return rooms that are available on a given date. Currently it reads:

        public IEnumerable<Room> GetAvaliabileByDate(DateTime date)
        {
            using (HotelsContext context = new HotelsContext(_options))
            {
                var roomsWithoutReservation =
                    (from reservation in context.Reservations
                     where date < reservation.CheckIn || date > reservation.CheckOut
                     select reservation.Room)
                    .ToList();

                return roomsWithoutReservation;
            }
        }

Unfortunately this only returns rooms that have at least one reservation outside of the time period.

**Comment by Peter-Schneider** [comment]
I've submitted a PR #138  to change the query.
