### ISSUE TITLE
Module 1 LAK Exercise 4, Task 1 Steps 5-6 

### ISSUE THREAD

**Issue by XtremeDR** [MicrosoftLearning/20487D-Developing-Microsoft-Azure-and-Web-Services#139]
When going through the steps using the Lab Answer Key the steps for creating the Web App + SQL DB are as follows:

**To display all the App Services, on the left menu panel, click App Services. 
To select the app service template, in the App Services blade, click Add.
To see an overview of the template, in the Web blade, click Web App + SQL.**

However, this functionality appears to have changed.  If you head to the App Services blade and select "Add" you will only have the Web App option, you cannot select the Web App + SQL template.  This functionality still exists, but you have to search under All Resources for "Web App + SQL" to find it.  

Thank you for your consideration.

**Comment by WigF1** [comment]
This is still an issue - is anyone looking into this?

**Comment by AviAvni** [comment]
Thanks fixed
