### ISSUE TITLE
Module 2: 'SQL Operations Studio' = Now known as 'Azure Data Studio'

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/20487D-Developing-Microsoft-Azure-and-Web-Services#140]
- Per this link, the tool 'SQL Operations Studio' is apparently now known as 'Azure Data Studio'
https://cloudblogs.microsoft.com/sqlserver/2018/08/30/the-august-release-of-sql-operations-studio-is-now-available/

- When this tool is installed per the Setup Guide, its desktop & menu icons only reference 'Azure Data Studio'

- For clarity's sake in Mod 2 Demo/Lab_Manual/LAK (and also MOD7 Demo?) instructs, references to the 'SQL Operations Studio' might be more clear if they referred to both old/new names?  

- i.e., perhaps instead use:  "...Open Azure Data Studio (SQL Operations Studio)..." or something similar.  If the older name is not going to be used again, it also might make sense to just drop it altogether and use only 'Azure Data Studio'.

**Comment by AviAvni** [comment]
Thanks fixed
