### ISSUE TITLE
20487D_MOD02_LAK.md Very minor typo

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/20487D-Developing-Microsoft-Azure-and-Web-Services#141]
- In Module 2/Lab B/Exercise 2/Task 4/Step 2 the CD command includes a reference to 'Lab1' in the CD dir path:

cd [Repository Root]\Allfiles\Mod02\LabFiles\Lab**1**\Starter\DAL.Test

- This should, presumably, be referring to Lab 2:

cd [Repository Root]\Allfiles\Mod02\LabFiles\Lab**2**\Starter\DAL.Test

**Comment by AviAvni** [comment]
Thanks fixed
