### ISSUE TITLE
Module 7 Lab B: Querying Graph Data unclear instructions on how to create Gremlin API graph

### ISSUE THREAD

**Issue by XtremeDR** [MicrosoftLearning/20487D-Developing-Microsoft-Azure-and-Web-Services#142]
In module 7B when attempting to use the "Add Graph" function in Azure to create the blueyonder graph the "Partition key" is a required field, but there are no instructions on how to fill out this field.

The instructions are as follows:
Task 1: Create a new Cosmos DB graph database in the Azure portal
Open the Azure portal.
In the left pane, click + Create a resource.
In the search box, type Azure Cosmos DB, from the search results select Azure Cosmos DB and then click Create.
In Account Name box, type blueyonder-destinations{YourInitials}.
In API, select Gremlin (graph).
In Resource Group section, select Create new, in the Name box type Mod07Lab2, click OK and then click Create.
Click Review + Create, click Create and then wait for the resource to be created.
To display all the resources, in the left pane, click All resources.
Click blueyonder-destinations{YourInitials}.
On the top bar, click + Add Graph.
In Database id, select Create new, and then type blueyonder.
In Graph Id, type traveler, and then click OK.

![image](https://user-images.githubusercontent.com/43967240/56431555-f659ea80-627e-11e9-969d-356bec587c2a.png)

**Comment by XtremeDR** [comment]
Continuing onward, there does not appear to be an "upload" function to select to upload the .json data in the next task either.  This Azure feature appears to have changed enough that the directions given here no longer work, and the documentation that Microsoft has on this feature is out of date as well. 

![image](https://user-images.githubusercontent.com/43967240/56432037-d75c5800-6280-11e9-8cfc-86f91b6cd4ad.png)

**Comment by AviAvni** [comment]
Thanks fixed
